### ISSUE TITLE
Use Case #2: Investor: withdraw money

### ISSUE THREAD

**Issue by jaronoff97** [ryan-bradford/solar-investment#24]
TRACK PROGRESS FOR the following use case:

* Investor: withdraw money

**Comment by ryan-bradford** [comment]
Relevant Wiki Page: https://github.com/ryan-bradford/solar-investment/wiki/Use-Case-%232:-Investor-Sells-Investments
Relevant Story Ticket: https://github.com/ryan-bradford/solar-investment/issues/19

Subtickets:
1. Investor should be able to select the amount of money to withdraw. (https://github.com/ryan-bradford/solar-investment/issues/14)
2. Build API for selling, reselling, and buying investments that allows queuing.
3. Connect the Transaction API to a banking system (PayPal, etc.)

**Comment by ryan-bradford** [comment]
Activity Diagram: https://github.com/ryan-bradford/solar-investment/wiki/Activity-Diagram-%232
State Diagram: https://github.com/ryan-bradford/solar-investment/wiki/State-Diagram-%232
Wireframes: https://github.com/ryan-bradford/solar-investment/wiki/Wireframes-%232
Instrumentation: https://github.com/ryan-bradford/solar-investment/wiki/Instrumentation-%232
