### ISSUE TITLE
RFC: Investment Marketplace API

### ISSUE THREAD

**Issue by ryan-bradford** [ryan-bradford/solar-investment#27]
We need to create a Marketplace for Creating, Buying, Selling, and Dividing investments.

API Endpoints:

POST /investments -> Called when a homeowners puts their home up for investment. Creates an investment from the given JSON Body details. Returns a list of investment ID.

GET /investments -> Returns a list of all investments in the platform. 

GET /investments/{investment_id} -> Returns information about the requested investment. 

GET /investments/investor/{user_id} -> Returns Information about all investments that this investor has.

POST /investments/{investment_id}/payment -> Called when a homeowner makes a payment for a specific investment. 

POST /investments/{investment_id}/sell -> Called when an investor Opts to sell a given investment. 

POST /investment/{investment_id}/buy -> Called when an investor buys an entire investment. 

POST /investment/{investment_id}/buy/{amount} -> Called when an investor buys part of an investment. This will create a new investment of size {amount} and edit {investment_id} to have {amount} less value.

**Comment by jaronoff97** [comment]
Sub-issues:

#20 
#21 
#12 
#19 
#18 
#22
